shop_api_address_checkout:
    path: /{token}/address
    methods: [PUT]
    defaults:
        _controller: sylius.shop_api_plugin.controller.checkout.address_action

shop_api_summarize_checkout:
    path: /{token}
    methods: [GET]
    defaults:
        _controller: sylius.shop_api_plugin.controller.checkout.summarize_action
