sylius_shop_api_product_show_details_by_slug_deprecated:
    path: /products-by-slug/{slug}
    methods: [GET]
    defaults:
        _controller: 'Symfony\Bundle\FrameworkBundle\Controller\RedirectController:urlRedirectAction'
        path: /shop-api/{channelCode}/products/by-slug/{slug}
        permanent: true

sylius_shop_api_add_product_review_by_slug_deprecated:
    path: /product-reviews-by-slug/{slug}
    methods: [POST]
    defaults:
        _controller: sylius.shop_api_plugin.controller.product.add_review_by_slug_action

sylius_shop_api_product_show_catalog_by_slug_deprecated:
    path: /taxon-products-by-slug/{taxonSlug}
    methods: [GET]
    defaults:
        _controller: sylius.shop_api_plugin.controller.product.show_product_catalog_by_taxon_slug_action

sylius_shop_api_product_show_reviews_by_slug_deprecated:
    path: /product-reviews-by-slug/{slug}
    methods: [GET]
    defaults:
        _controller: sylius.shop_api_plugin.controller.product.show_product_reviews_by_slug_action

# New routes
sylius_shop_api_product_show_details_by_slug:
    path: /products/by-slug/{slug}
    methods: [GET]
    defaults:
        _controller: sylius.shop_api_plugin.controller.product.show_product_details_by_slug_action

sylius_shop_api_product_show_catalog_by_slug:
    path: /taxon-products/by-slug/{slug}
    methods: [GET]
    defaults:
        _controller: sylius.shop_api_plugin.controller.product.show_product_catalog_by_taxon_slug_action

sylius_shop_api_product_show_reviews_by_slug:
    path: /product/by-slug/{slug}/reviews
    methods: [GET]
    defaults:
        _controller: sylius.shop_api_plugin.controller.product.show_product_reviews_by_slug_action

sylius_shop_api_add_product_review_by_slug:
    path: /product/by-slug/{slug}/reviews
    methods: [POST]
    defaults:
        _controller: sylius.shop_api_plugin.controller.product.add_review_by_slug_action
