shop_api_product_show_details:
    path: /products/{slug}
    methods: [GET]
    defaults:
        _controller: sylius.shop_api_plugin.controller.product.show_product_details_action

shop_api_add_product_review:
    path: /products/{slug}/reviews
    methods: [POST]
    defaults:
        _controller: sylius.shop_api_plugin.controller.product.add_review_action

shop_api_product_show_catalog:
    path: /taxon-products/{taxonomySlug}
    methods: [GET]
    defaults:
        _controller: sylius.shop_api_plugin.controller.product.show_product_catalog_action
    requirements:
        taxonomySlug: .+

shop_api_product_show_reviews:
    path: /products/{slug}/reviews
    methods: [GET]
    defaults:
        _controller: sylius.shop_api_plugin.controller.product.show_reviews_action
