shop_api_taxon_show_details:
    path: /taxons/{slug}
    methods: [GET]
    defaults:
        _controller: sylius.shop_api_plugin.controller.taxon_controller:showDetailsAction
    requirements:
        slug: .+

shop_api_taxon_show_tree:
    path: /taxons/
    methods: [GET]
    defaults:
        _controller: sylius.shop_api_plugin.controller.taxon_controller:showTreeAction
