language: php

php:
    - 7.1
    - 7.0
    - 5.6

cache:
    directories:
        - ~/.composer/cache/files

before_install:
    - phpenv config-rm xdebug.ini || true
    - echo "memory_limit=4096M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
    - composer update --prefer-dist

before_script:
    - (cd tests/Application && bin/console doctrine:schema:create --env=test)

script:
    - composer validate --strict
    - vendor/bin/phpspec run
    - vendor/bin/phpunit --process-isolation
