shop_api_cart:
    resource: "@ShopApiPlugin/Resources/config/routing/cart.yml"

shop_api_product:
    resource: "@ShopApiPlugin/Resources/config/routing/product.yml"

shop_api_taxon:
    resource: "@ShopApiPlugin/Resources/config/routing/taxon.yml"
