shop_api_provide_cart:
    path: /shop-api/carts/{token}
    methods: [POST]
    defaults:
        _controller: ShopApiPlugin:Cart:create

shop_api_cart_summary:
    path: /shop-api/carts/{token}
    methods: [GET]
    defaults:
        _controller: ShopApiPlugin:Cart:summary
