shop_api_cart:
    resource: "@ShopApiPlugin/Resources/config/routing/cart.yml"
    prefix: /shop-api

shop_api_product:
    resource: "@ShopApiPlugin/Resources/config/routing/product.yml"
    prefix: /shop-api

shop_api_taxon:
    resource: "@ShopApiPlugin/Resources/config/routing/taxon.yml"
    prefix: /shop-api

shop_api_register:
    resource: "@ShopApiPlugin/Resources/config/routing/register.yml"
    prefix: /shop-api

shop_api_checkout:
    resource: "@ShopApiPlugin/Resources/config/routing/checkout.yml"
    prefix: /shop-api/checkout
