jms_serializer:
    metadata:
        directories:
            sylius-shop-api:
                namespace_prefix: "Sylius\\ShopApiPlugin\\View"
                path: "@ShopApiPlugin/Resources/config/serializer"
tactician:
    commandbus:
        default:
            middleware:
                - tactician.middleware.doctrine
                - tactician.middleware.command_handler
