jms_serializer:
    metadata:
        directories:
            sylius-shop-api_taxon:
                namespace_prefix: "Sylius\\ShopApiPlugin\\View\\Taxon"
                path: "@ShopApiPlugin/Resources/config/serializer/Taxon"
            sylius-shop-api_product:
                namespace_prefix: "Sylius\\ShopApiPlugin\\View\\Product"
                path: "@ShopApiPlugin/Resources/config/serializer/Product"
tactician:
    commandbus:
        default:
            middleware:
                - tactician.middleware.doctrine
                - tactician.middleware.command_handler

sylius_customer:
    resources:
        customer:
            classes:
                controller: Sylius\ShopApiPlugin\Controller\Customer\CustomerController
